# Generated by Django 3.0.3 on 2020-02-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20200219_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': ' A lot of Subscribers'},
        ),
    ]
